## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName
    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

class _ARRW:
     def __init__(self, obj, index):
         self.obj = obj
         self.index = index
     def __lshift__(self, r):
         self.obj[self.index] = r

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import stages.py_stageProgressor;
import stages.stageProgressor as stageProgressor
# (Line 3) var currentStage = 0;
currentStage = EUDVariable(0)
# (Line 5) function setStage(stage) {
@EUDFunc
def f_setStage(stage):
    # (Line 6) currentStage = stage;
    currentStage << (stage)
    # (Line 7) }
    # (Line 9) function getStage(stage) {

@EUDFunc
def f_getStage(stage):
    # (Line 10) return currentStage;
    EUDReturn(currentStage)
    # (Line 11) }
