## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName
    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

class _ARRW:
     def __init__(self, obj, index):
         self.obj = obj
         self.index = index
     def __lshift__(self, r):
         self.obj[self.index] = r

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import player.playerProc as pProc;
import player._epspy.playerProc as pProc
# (Line 2) import player.lifesys;
import player._epspy.lifesys as lifesys
# (Line 4) import bulletBase as bBase;
import _epspy.bulletBase as bBase
# (Line 5) import bulletTools as bTool;
import _epspy.bulletTools as bTool
# (Line 7) import unitloop as uLoop;
import _epspy.unitloop as uLoop
# (Line 8) import stages.stagesys as sSys;
import stages._epspy.stagesys as sSys
# (Line 10) function setBulletFlingy(flingyID) {
@EUDFunc
def f_setBulletFlingy(flingyID):
    # (Line 11) dwwrite(0x6C9930 + 4 * flingyID, 1);
    # (Line 12) }
    f_dwwrite(0x6C9930 + 4 * flingyID, 1)
    # (Line 14) function onPluginStart() {

@EUDFunc
def onPluginStart():
    # (Line 15) lifesys.addLife($Force1, 10);
    # (Line 18) SetMemory(0x6644F8, SetTo, 0x4B584A0F);  // 마린 그래픽을 0F(저글링)으로
    lifesys.f_addLife(18, 10)
    # (Line 19) SetMemory(0x51783C, SetTo, 0x00E90009);  // 버튼셋 그래픽 변경
    # (Line 20) SetMemory(0x6616E0, Add, 130);  // 마린의 지상무기 삭제
    # (Line 21) SetMemory(0x6636B8, Add, 130);  // 마린의 공중무기 삭제
    # (Line 23) setBulletFlingy(43);  // 스카웃 속도 조절
    DoActions([
        SetMemory(0x6644F8, SetTo, 0x4B584A0F),
        SetMemory(0x51783C, SetTo, 0x00E90009),
        SetMemory(0x6616E0, Add, 130),
        SetMemory(0x6636B8, Add, 130)
    ])
    # (Line 24) }
    f_setBulletFlingy(43)
    # (Line 26) var x = 0;

x = EUDVariable(0)
# (Line 27) var timer = 0;
timer = EUDVariable(0)
# (Line 29) function afterTriggerExec() {
@EUDFunc
def afterTriggerExec():
    # (Line 30) pProc.regeneratePlayers();
    # (Line 31) uLoop.mainUnitLoop();
    pProc.f_regeneratePlayers()
    # (Line 32) sSys.runStageProc();
    uLoop.f_mainUnitLoop()
    # (Line 34) SetCurrentPlayer(getuserplayerid());
    sSys.f_runStageProc()
    # (Line 35) MinimapPing('minimapPing');
    # (Line 37) SetMemory(0x6D5E1C, SetTo, 1);
    DoActions([
        SetCurrentPlayer(f_getuserplayerid())
    ])
    # (Line 38) }
    DoActions([
        MinimapPing('minimapPing'),
        SetMemory(0x6D5E1C, SetTo, 1)
    ])
